In [27]:
import pandas as pd

In [28]:
voting_data = pd.read_csv("data/voting_VA.csv")
voting_data

,Unnamed: 0,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,11161,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,AL GORE,DEMOCRAT,5092,11925,20220315,TOTAL
1,11162,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,6352,11925,20220315,TOTAL
2,11163,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,RALPH NADER,GREEN,220,11925,20220315,TOTAL
3,11164,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,OTHER,OTHER,261,11925,20220315,TOTAL
4,11165,2000,VIRGINIA,VA,ALBEMARLE,51003,US PRESIDENT,AL GORE,DEMOCRAT,16255,36846,20220315,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3731,71966,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,OTHER,OTHER,24,12113,20220315,ELECTION DAY
3732,71967,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,OTHER,OTHER,0,12113,20220315,PROVISIONAL
3733,71968,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,2825,12113,20220315,ABSENTEE
3734,71969,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,2370,12113,20220315,ELECTION DAY
3735,71970,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,26,12113,20220315,PROVISIONAL

It seems as though we have some useless columns, so let's go ahead and drop some:

In [29]:
cleaned_voting = voting_data.drop(columns=['Unnamed: 0', 'version', 'mode'])
cleaned_voting

,year,state,state_po,county_name,county_fips,office,candidate,party,candidatevotes,totalvotes
0,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,AL GORE,DEMOCRAT,5092,11925
1,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,GEORGE W. BUSH,REPUBLICAN,6352,11925
2,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,RALPH NADER,GREEN,220,11925
3,2000,VIRGINIA,VA,ACCOMACK,51001,US PRESIDENT,OTHER,OTHER,261,11925
4,2000,VIRGINIA,VA,ALBEMARLE,51003,US PRESIDENT,AL GORE,DEMOCRAT,16255,36846
...,...,...,...,...,...,...,...,...,...,...
3731,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,OTHER,OTHER,24,12113
3732,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,OTHER,OTHER,0,12113
3733,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,2825,12113
3734,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,2370,12113
3735,2020,VIRGINIA,VA,WINCHESTER CITY,51840,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,26,12113

It also feels as if we don't really need the office, state_po, or state column as we are only working with virginia data and the entire CSV only contains Virginia data, so we can remove those columns as well. Office stays as US President throughout the CSV as well.

In [30]:
dropped = ['office', 'state', 'state_po']
cleaned_voting.drop(dropped, axis=1,inplace=True)
cleaned_voting

,year,county_name,county_fips,candidate,party,candidatevotes,totalvotes
0,2000,ACCOMACK,51001,AL GORE,DEMOCRAT,5092,11925
1,2000,ACCOMACK,51001,GEORGE W. BUSH,REPUBLICAN,6352,11925
2,2000,ACCOMACK,51001,RALPH NADER,GREEN,220,11925
3,2000,ACCOMACK,51001,OTHER,OTHER,261,11925
4,2000,ALBEMARLE,51003,AL GORE,DEMOCRAT,16255,36846
...,...,...,...,...,...,...,...
3731,2020,WINCHESTER CITY,51840,OTHER,OTHER,24,12113
3732,2020,WINCHESTER CITY,51840,OTHER,OTHER,0,12113
3733,2020,WINCHESTER CITY,51840,DONALD J TRUMP,REPUBLICAN,2825,12113
3734,2020,WINCHESTER CITY,51840,DONALD J TRUMP,REPUBLICAN,2370,12113
3735,2020,WINCHESTER CITY,51840,DONALD J TRUMP,REPUBLICAN,26,12113

Now let's see if we have missing values:

In [31]:
cleaned_voting.isnull().sum()

year              0
county_name       0
county_fips       0
candidate         0
party             0
candidatevotes    0
totalvotes        0
dtype: int64

With no missing values to handle, lets observe types.

In [32]:
cleaned_voting.dtypes

year               int64
county_name       object
county_fips        int64
candidate         object
party             object
candidatevotes     int64
totalvotes         int64
dtype: object

There isn't any conflicting types, but we can change the party to a category (may make future analysis easier)

In [33]:
cleaned_voting['party'] = cleaned_voting['party'].astype('category')

Now let's check uniqueness:

In [34]:
cleaned_voting['candidate'].unique()

array(['AL GORE', 'GEORGE W. BUSH', 'RALPH NADER', 'OTHER', 'JOHN KERRY',
       'BARACK OBAMA', 'JOHN MCCAIN', 'MITT ROMNEY', 'HILLARY CLINTON',
       'DONALD TRUMP', 'JOSEPH R BIDEN JR', 'JO JORGENSEN',
       'DONALD J TRUMP'], dtype=object)

There seems to be two trump coluns, so let's go ahead and replace one of them.

In [35]:
cleaned_voting['candidate'].replace('DONALD J TRUMP', 'DONALD TRUMP', inplace=True)
cleaned_voting['candidate'].unique()

array(['AL GORE', 'GEORGE W. BUSH', 'RALPH NADER', 'OTHER', 'JOHN KERRY',
       'BARACK OBAMA', 'JOHN MCCAIN', 'MITT ROMNEY', 'HILLARY CLINTON',
       'DONALD TRUMP', 'JOSEPH R BIDEN JR', 'JO JORGENSEN'], dtype=object)

In [36]:
cleaned_voting['county_name'].duplicated().sum()

3569

So there seems to be some cities with both the city and non city suffixes, which we have to standardize across both datasets (county dataset seems to also be problematic).

In [37]:
cleaned_voting['county_name'].replace({
    'ALEXANDRIA': 'ALEXANDRIA CITY',
    'BRISTOL': 'BRISTOL CITY',
    'BUENA VISTA': 'BUENA VISTA CITY',
    'CharlesCty': 'CHARLES CITY',
    'CHARLOTTESVILLE': 'CHARLOTTESVILLE CITY',
    'CHESAPEAKE': 'CHESAPEAKE CITY',
    'COLONIAL HEIGHTS': 'COLONIAL HEIGHTS CITY',
    'COVINGTON': 'COVINGTON CITY',
    'DANVILLE': 'DANVILLE CITY',
    'EMPORIA': 'EMPORIA CITY',
    'FAIRFAX': 'FAIRFAX CITY',
    'FALLS CHURCH': 'FALLS CHURCH CITY',
    'FREDERICKSBURG': 'FREDERICKSBURG CITY',
    'HAMPTON': 'HAMPTON CITY',
    'HARRISONBURG': 'HARRISONBURG CITY',
    'LEXINGTON': 'LEXINGTON CITY',
    'LYNCHBURG': 'LYNCHBURG CITY',
    'MANASSAS': 'MANASSAS CITY',
    'MARTINSVILLE': 'MARTINSVILLE CITY',
    'NEWPORT NEWS': 'NEWPORT NEWS CITY',
    'NORFOLK': 'NORFOLK CITY',
    'NORTON': 'NORTON CITY',
    'PETERSBURG': 'PETERSBURG CITY',
    'POQUOSON': 'POQUOSON CITY',
    'PORTSMOUTH': 'PORTSMOUTH CITY',
    'RADFORD': 'RADFORD CITY',
    'SALEM': 'SALEM CITY',
    'STAUNTON': 'STAUNTON CITY',
    'SUFFOLK': 'SUFFOLK CITY',
    'VIRGINIA BEACH': 'VIRGINIA BEACH CITY',
    'WAYNESBORO': 'WAYNESBORO CITY',
    'WILLIAMSBURG': 'WILLIAMSBURG CITY',
    'WINCHESTER': 'WINCHESTER CITY'
}, inplace=True)

cleaned_voting['county_name'].unique()

array(['ACCOMACK', 'ALBEMARLE', 'ALLEGHANY', 'AMELIA', 'AMHERST',
       'APPOMATTOX', 'ARLINGTON', 'AUGUSTA', 'BATH', 'BEDFORD', 'BLAND',
       'BOTETOURT', 'BRUNSWICK', 'BUCHANAN', 'BUCKINGHAM', 'CAMPBELL',
       'CAROLINE', 'CARROLL', 'CHARLES CITY', 'CHARLOTTE', 'CHESTERFIELD',
       'CLARKE', 'CRAIG', 'CULPEPER', 'CUMBERLAND', 'DICKENSON',
       'DINWIDDIE', 'ESSEX', 'FAIRFAX CITY', 'FAUQUIER', 'FLOYD',
       'FLUVANNA', 'FRANKLIN', 'FREDERICK', 'GILES', 'GLOUCESTER',
       'GOOCHLAND', 'GRAYSON', 'GREENE', 'GREENSVILLE', 'HALIFAX',
       'HANOVER', 'HENRICO', 'HENRY', 'HIGHLAND', 'ISLE OF WIGHT',
       'JAMES CITY', 'KING AND QUEEN', 'KING GEORGE', 'KING WILLIAM',
       'LANCASTER', 'LEE', 'LOUDOUN', 'LOUISA', 'LUNENBURG', 'MADISON',
       'MATHEWS', 'MECKLENBURG', 'MIDDLESEX', 'MONTGOMERY', 'NELSON',
       'NEW KENT', 'NORTHAMPTON', 'NORTHUMBERLAND', 'NOTTOWAY', 'ORANGE',
       'PAGE', 'PATRICK', 'PITTSYLVANIA', 'POWHATAN', 'PRINCE EDWARD',
       'PRINCE GEORGE', 'PRINCE WILLIAM', 'PULASKI', 'RAPPAHANNOCK',
       'RICHMOND', 'ROANOKE', 'ROCKBRIDGE', 'ROCKINGHAM', 'RUSSELL',
       'SCOTT', 'SHENANDOAH', 'SMYTH', 'SOUTHAMPTON', 'SPOTSYLVANIA',
       'STAFFORD', 'SURRY', 'SUSSEX', 'TAZEWELL', 'WARREN', 'WASHINGTON',
       'WESTMORELAND', 'WISE', 'WYTHE', 'YORK', 'ALEXANDRIA CITY',
       'BRISTOL CITY', 'BUENA VISTA CITY', 'CHARLOTTESVILLE CITY',
       'CHESAPEAKE CITY', 'COLONIAL HEIGHTS CITY', 'COVINGTON CITY',
       'DANVILLE CITY', 'EMPORIA CITY', 'FALLS CHURCH CITY',
       'FREDERICKSBURG CITY', 'GALAX', 'HAMPTON CITY',
       'HARRISONBURG CITY', 'HOPEWELL', 'LEXINGTON CITY',
       'LYNCHBURG CITY', 'MANASSAS CITY', 'MANASSAS PARK',
       'MARTINSVILLE CITY', 'NEWPORT NEWS CITY', 'NORFOLK CITY',
       'NORTON CITY', 'PETERSBURG CITY', 'POQUOSON CITY',
       'PORTSMOUTH CITY', 'RADFORD CITY', 'SALEM CITY', 'STAUNTON CITY',
       'SUFFOLK CITY', 'VIRGINIA BEACH CITY', 'WAYNESBORO CITY',
       'WILLIAMSBURG CITY', 'WINCHESTER CITY', 'FRANKLIN CITY',
       'GALAX CITY', 'HOPEWELL CITY', 'MANASSAS PARK CITY',
       'RICHMOND CITY', 'ROANOKE CITY'], dtype=object)

Now, we want to combine our results and deal with duplicated values at the same time.

In [39]:
# cleaned_voting_copy = cleaned_voting.copy()
# combined_voting = cleaned_voting_copy.groupby(
#     ['year', 'county_name', 'county_fips', 'candidate', 'party', 'totalvotes'],
#     as_index=False
# )['candidatevotes'].sum()

# This is the code that should be used to do this, but caused a memory error for some reason, so we will have to do it manually

In [44]:
cleaned_voting_copy = cleaned_voting.copy()
combinations_unique = cleaned_voting.drop(columns=['candidatevotes']).drop_duplicates()

for idx, row in combinations_unique.iterrows():
    filter = cleaned_voting[
        (cleaned_voting['year'] == row['year']) &
        (cleaned_voting['county_name'] == row['county_name']) &
        (cleaned_voting['county_fips'] == row['county_fips']) &
        (cleaned_voting['candidate'] == row['candidate']) &
        (cleaned_voting['party'] == row['party']) &
        (cleaned_voting['totalvotes'] == row['totalvotes'])
    ]

    combinations_votes = filter['candidatevotes'].sum()
    combined_row = row.copy()
    combined_row['candidatevotes'] = combinations_votes
    cleaned_voting_copy = pd.concat([cleaned_voting_copy, pd.DataFrame([combined_row])], ignore_index=True)

In [45]:
cleaned_voting_copy

,year,county_name,county_fips,candidate,party,candidatevotes,totalvotes
0,2000,ACCOMACK,51001,AL GORE,DEMOCRAT,5092,11925
1,2000,ACCOMACK,51001,GEORGE W. BUSH,REPUBLICAN,6352,11925
2,2000,ACCOMACK,51001,RALPH NADER,GREEN,220,11925
3,2000,ACCOMACK,51001,OTHER,OTHER,261,11925
4,2000,ALBEMARLE,51003,AL GORE,DEMOCRAT,16255,36846
...,...,...,...,...,...,...,...
6407,2020,WILLIAMSBURG CITY,51830,DONALD TRUMP,REPUBLICAN,1963,6890
6408,2020,WINCHESTER CITY,51840,JOSEPH R BIDEN JR,DEMOCRAT,6610,12113
6409,2020,WINCHESTER CITY,51840,JO JORGENSEN,LIBERTARIAN,213,12113
6410,2020,WINCHESTER CITY,51840,OTHER,OTHER,69,12113
6411,2020,WINCHESTER CITY,51840,DONALD TRUMP,REPUBLICAN,5221,12113

In [46]:
cleaned_voting_copy.to_csv("cleaned_voting.csv",index=False)

Now that the voting data is cleaned, let's clean the county data

In [48]:
county_data = pd.read_csv("data/county_adjacencies.csv")
county_data

,County,Population2022,FIPS,District,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12
0,Accomack,33191,51001,2,Northumberland,Lancaster,Middlesex,Mathews,Northampton,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albemarle,114534,51003,5,CharlottesvilleCity,Nelson,Augusta,Rockingham,Greene,Orange,Louisa,Fluvanna,Buckingham,Nelson,NaN,NaN
2,AlexandriaCity,155525,51510,8,Fairfax,Arlington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alleghany,14835,51005,6,Craig,Bath,Botetourt,CovingtonCity,Rockbridge,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Amelia,13455,51007,5,PrinceEdward,Cumberland,Powhatan,Chesterfield,Dinwiddie,Nottoway,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,WinchesterCity,27936,51840,6,Frederick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129,Wise,35421,51195,9,Lee,Scott,Dickenson,NortonCity,Russell,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,Wythe,28111,51197,9,Bland,Smyth,Grayson,Carroll,Pulaski,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131,York,71341,51199,1,Gloucester,JamesCty,WilliamsburgCity,NewportNewsCity,PoquosonCity,HamptonCity,Northampton,NaN,NaN,NaN,NaN,NaN
132,WilliamsburgCity,15920,51830,1,JamesCty,York,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

There is very clearly problematic city names, so let's go ahead and fix that:

In [50]:
county_data['County'] = county_data['County'].str.replace('City', ' City', regex=False).replace('Cty', ' City', regex=False).str.upper()

# Apply specific corrections with a dictionary mapping for known issues
corrections = {
    'BUENAVISTA CITY': 'BUENA VISTA CITY',
    'COLONIALHEIGHTS CITY': 'COLONIAL HEIGHTS CITY',
    'FALLSCHURCH CITY': 'FALLS CHURCH CITY',
    'ISLEOFWIGHT': 'ISLE OF WIGHT',
    'KINGANDQUEEN': 'KING AND QUEEN',
    'KINGGEORGE': 'KING GEORGE',
    'KINGWILLIAM': 'KING WILLIAM',
    'MANASSASPARK CITY': 'MANASSAS PARK CITY',
    'NEWKENT': 'NEW KENT',
    'NEWPORTNEWS CITY': 'NEWPORT NEWS CITY',
    'PRINCEEDWARD': 'PRINCE EDWARD',
    'PRINCEGEORGE': 'PRINCE GEORGE',
    'PRINCEWILLIAM': 'PRINCE WILLIAM',
    'VIRGINIABEACH CITY': 'VIRGINIA BEACH CITY'
}

# Apply corrections
county_data['County'] = county_data['County'].replace(corrections)

In [52]:
county_data['County'].unique()

array(['ACCOMACK', 'ALBEMARLE', 'ALEXANDRIA CITY', 'ALLEGHANY', 'AMELIA',
       'AMHERST', 'APPOMATTOX', 'ARLINGTON', 'AUGUSTA', 'BATH', 'BEDFORD',
       'BLAND', 'BOTETOURT', 'BRISTOL CITY', 'BRUNSWICK', 'BUCHANAN',
       'BUCKINGHAM', 'BUENA VISTA CITY', 'CAMPBELL', 'CAROLINE',
       'CARROLL', 'CHARLESCTY', 'CHARLOTTE', 'CHARLOTTESVILLE CITY',
       'CHESAPEAKE CITY', 'CHESTERFIELD', 'CLARKE',
       'COLONIAL HEIGHTS CITY', 'COVINGTON CITY', 'CRAIG', 'CULPEPER',
       'CUMBERLAND', 'DANVILLE CITY', 'DICKENSON', 'DINWIDDIE',
       'EMPORIA CITY', 'ESSEX', 'FAIRFAX', 'FAIRFAX CITY',
       'FALLS CHURCH CITY', 'FAUQUIER', 'FLOYD', 'FLUVANNA', 'FRANKLIN',
       'FRANKLIN CITY', 'FREDERICK', 'FREDERICKSBURG CITY', 'GALAX CITY',
       'GILES', 'GLOUCESTER', 'GOOCHLAND', 'GRAYSON', 'GREENE',
       'GREENSVILLE', 'HALIFAX', 'HAMPTON CITY', 'HANOVER',
       'HARRISONBURG CITY', 'HENRICO', 'HENRY', 'HIGHLAND',
       'HOPEWELL CITY', 'ISLE OF WIGHT', 'JAMESCTY', 'KING AND QUEEN',
       'KING GEORGE', 'KING WILLIAM', 'LANCASTER', 'LEE',
       'LEXINGTON CITY', 'LOUDOUN', 'LOUISA', 'LUNENBURG',
       'LYNCHBURG CITY', 'MADISON', 'MANASSAS CITY', 'MANASSAS PARK CITY',
       'MARTINSVILLE CITY', 'MATHEWS', 'MECKLENBURG', 'MIDDLESEX',
       'MONTGOMERY', 'NELSON', 'NEW KENT', 'NEWPORT NEWS CITY',
       'NORFOLK CITY', 'NORTHAMPTON', 'NORTHUMBERLAND', 'NORTON CITY',
       'NOTTOWAY', 'ORANGE', 'PAGE', 'PATRICK', 'PETERSBURG CITY',
       'PITTSYLVANIA', 'POQUOSON CITY', 'PORTSMOUTH CITY', 'POWHATAN',
       'PRINCE EDWARD', 'PRINCE GEORGE', 'PRINCE WILLIAM', 'PULASKI',
       'RADFORD CITY', 'RAPPAHANNOCK', 'RICHMOND', 'RICHMOND CITY',
       'ROANOKE', 'ROANOKE CITY', 'ROCKBRIDGE', 'ROCKINGHAM', 'RUSSELL',
       'SALEM CITY', 'SCOTT', 'SHENANDOAH', 'SMYTH', 'SOUTHAMPTON',
       'SPOTSYLVANIA', 'STAFFORD', 'STAUNTON CITY', 'SUFFOLK CITY',
       'SURRY', 'SUSSEX', 'TAZEWELL', 'VIRGINIA BEACH CITY', 'WARREN',
       'WASHINGTON', 'WAYNESBORO CITY', 'WESTMORELAND', 'WINCHESTER CITY',
       'WISE', 'WYTHE', 'YORK', 'WILLIAMSBURG CITY'], dtype=object)

It seems that we missed Jamescty and Charlescty, so let's fix that

In [53]:
additional_corrections = {
    'CHARLESCTY': 'CHARLES CITY',
    'JAMESCTY': 'JAMES CITY'
}

# Apply additional corrections
county_data['County'] = county_data['County'].replace(additional_corrections)

In [55]:
county_data['County'].unique()

array(['ACCOMACK', 'ALBEMARLE', 'ALEXANDRIA CITY', 'ALLEGHANY', 'AMELIA',
       'AMHERST', 'APPOMATTOX', 'ARLINGTON', 'AUGUSTA', 'BATH', 'BEDFORD',
       'BLAND', 'BOTETOURT', 'BRISTOL CITY', 'BRUNSWICK', 'BUCHANAN',
       'BUCKINGHAM', 'BUENA VISTA CITY', 'CAMPBELL', 'CAROLINE',
       'CARROLL', 'CHARLES CITY', 'CHARLOTTE', 'CHARLOTTESVILLE CITY',
       'CHESAPEAKE CITY', 'CHESTERFIELD', 'CLARKE',
       'COLONIAL HEIGHTS CITY', 'COVINGTON CITY', 'CRAIG', 'CULPEPER',
       'CUMBERLAND', 'DANVILLE CITY', 'DICKENSON', 'DINWIDDIE',
       'EMPORIA CITY', 'ESSEX', 'FAIRFAX', 'FAIRFAX CITY',
       'FALLS CHURCH CITY', 'FAUQUIER', 'FLOYD', 'FLUVANNA', 'FRANKLIN',
       'FRANKLIN CITY', 'FREDERICK', 'FREDERICKSBURG CITY', 'GALAX CITY',
       'GILES', 'GLOUCESTER', 'GOOCHLAND', 'GRAYSON', 'GREENE',
       'GREENSVILLE', 'HALIFAX', 'HAMPTON CITY', 'HANOVER',
       'HARRISONBURG CITY', 'HENRICO', 'HENRY', 'HIGHLAND',
       'HOPEWELL CITY', 'ISLE OF WIGHT', 'JAMES CITY', 'KING AND QUEEN',
       'KING GEORGE', 'KING WILLIAM', 'LANCASTER', 'LEE',
       'LEXINGTON CITY', 'LOUDOUN', 'LOUISA', 'LUNENBURG',
       'LYNCHBURG CITY', 'MADISON', 'MANASSAS CITY', 'MANASSAS PARK CITY',
       'MARTINSVILLE CITY', 'MATHEWS', 'MECKLENBURG', 'MIDDLESEX',
       'MONTGOMERY', 'NELSON', 'NEW KENT', 'NEWPORT NEWS CITY',
       'NORFOLK CITY', 'NORTHAMPTON', 'NORTHUMBERLAND', 'NORTON CITY',
       'NOTTOWAY', 'ORANGE', 'PAGE', 'PATRICK', 'PETERSBURG CITY',
       'PITTSYLVANIA', 'POQUOSON CITY', 'PORTSMOUTH CITY', 'POWHATAN',
       'PRINCE EDWARD', 'PRINCE GEORGE', 'PRINCE WILLIAM', 'PULASKI',
       'RADFORD CITY', 'RAPPAHANNOCK', 'RICHMOND', 'RICHMOND CITY',
       'ROANOKE', 'ROANOKE CITY', 'ROCKBRIDGE', 'ROCKINGHAM', 'RUSSELL',
       'SALEM CITY', 'SCOTT', 'SHENANDOAH', 'SMYTH', 'SOUTHAMPTON',
       'SPOTSYLVANIA', 'STAFFORD', 'STAUNTON CITY', 'SUFFOLK CITY',
       'SURRY', 'SUSSEX', 'TAZEWELL', 'VIRGINIA BEACH CITY', 'WARREN',
       'WASHINGTON', 'WAYNESBORO CITY', 'WESTMORELAND', 'WINCHESTER CITY',
       'WISE', 'WYTHE', 'YORK', 'WILLIAMSBURG CITY'], dtype=object)

Now let's do the same thing (essentially) but for the N1-N12 columns

In [56]:
# Define the columns to be reformatted
n_cols = ['N1', 'N2', 'N3', 'N4', 'N5', 'N6', 'N7', 'N8', 'N9', 'N10', 'N11', 'N12']

# Apply standard formatting to all specified columns
county_data[n_cols] = county_data[n_cols].apply(lambda col: col.str.replace('City', ' City', regex=False).replace('Cty', ' City', regex=False).str.upper())

# Define corrections for specific formatting issues across all these columns
corrections = {
    'BUENAVISTA CITY': 'BUENA VISTA CITY',
    'COLONIALHEIGHTS CITY': 'COLONIAL HEIGHTS CITY',
    'FALLSCHURCH CITY': 'FALLS CHURCH CITY',
    'ISLEOFWIGHT': 'ISLE OF WIGHT',
    'KINGANDQUEEN': 'KING AND QUEEN',
    'KINGGEORGE': 'KING GEORGE',
    'KINGWILLIAM': 'KING WILLIAM',
    'MANASSASPARK CITY': 'MANASSAS PARK CITY',
    'NEWKENT': 'NEW KENT',
    'NEWPORTNEWS CITY': 'NEWPORT NEWS CITY',
    'PRINCEEDWARD': 'PRINCE EDWARD',
    'PRINCEGEORGE': 'PRINCE GEORGE',
    'PRINCEWILLIAM': 'PRINCE WILLIAM',
    'VIRGINIABEACH CITY': 'VIRGINIA BEACH CITY',
    'CHARLESCTY': 'CHARLES CITY',
    'JAMESCTY': 'JAMES CITY'
}

# Apply corrections to all specified columns
county_data[n_cols] = county_data[n_cols].replace(corrections)

Now let's make sure the column names match up with the column names of the voting data so that they can be merged

In [59]:
county_data.rename(columns={'County': 'county_name'}, inplace=True)
county_data.rename(columns={'FIPS': 'county_fips'}, inplace=True)
county_data.rename(columns={'Population2022': 'population_2022'}, inplace=True)
county_data.rename(columns={'District': 'district'}, inplace=True)

Let's make sure we put the county data into its own csv.

In [62]:
county_data.to_csv("cleaned_county.csv",index=False)

Now, we can merge the two datasets together

In [61]:
merged_data = pd.merge(cleaned_voting, county_data, on=['county_name', 'county_fips'], how='inner')
merged_data

,year,county_name,county_fips,candidate,party,candidatevotes,totalvotes,population_2022,district,N1,...,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12
0,2000,ACCOMACK,51001,AL GORE,DEMOCRAT,5092,11925,33191,2,NORTHUMBERLAND,...,MIDDLESEX,MATHEWS,NORTHAMPTON,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,ACCOMACK,51001,GEORGE W. BUSH,REPUBLICAN,6352,11925,33191,2,NORTHUMBERLAND,...,MIDDLESEX,MATHEWS,NORTHAMPTON,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,ACCOMACK,51001,RALPH NADER,GREEN,220,11925,33191,2,NORTHUMBERLAND,...,MIDDLESEX,MATHEWS,NORTHAMPTON,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,ACCOMACK,51001,OTHER,OTHER,261,11925,33191,2,NORTHUMBERLAND,...,MIDDLESEX,MATHEWS,NORTHAMPTON,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004,ACCOMACK,51001,JOHN KERRY,DEMOCRAT,5518,13356,33191,2,NORTHUMBERLAND,...,MIDDLESEX,MATHEWS,NORTHAMPTON,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3591,2020,ROANOKE CITY,51770,OTHER,OTHER,80,43323,97847,6,ROANOKE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3592,2020,ROANOKE CITY,51770,OTHER,OTHER,2,43323,97847,6,ROANOKE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3593,2020,ROANOKE CITY,51770,DONALD TRUMP,REPUBLICAN,7594,43323,97847,6,ROANOKE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3594,2020,ROANOKE CITY,51770,DONALD TRUMP,REPUBLICAN,7856,43323,97847,6,ROANOKE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3595,2020,ROANOKE CITY,51770,DONALD TRUMP,REPUBLICAN,157,43323,97847,6,ROANOKE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
merged_data.to_csv("merged_data.csv",index=False)